const metricLimits = [
  {
    key: "load_time_ms",
    label: "Load Time",
    unit: "ms",
    min: 0,
    max: 4000,
    thresholds: { good: 1000, medium: 3000 },
    ascending: false,
  },
  {
    key: "page_size_kb",
    label: "Page Size",
    unit: "KB",
    min: 0,
    max: 2000,
    thresholds: { good: 500, medium: 1500 },
    ascending: false,
  },
  {
    key: "first_contentful_paint_ms",
    label: "First Contentful Paint",
    unit: "ms",
    min: 0,
    max: 4000,
    thresholds: { good: 1000, medium: 3000 },
    ascending: false,
  },
  {
    key: "largest_contentful_paint_ms",
    label: "Largest Contentful Paint",
    unit: "ms",
    min: 0,
    max: 5000,
    thresholds: { good: 2500, medium: 4000 },
    ascending: false,
  },
  {
    key: "total_blocking_time_ms",
    label: "Total Blocking Time",
    unit: "ms",
    min: 0,
    max: 1000,
    thresholds: { good: 200, medium: 600 },
    ascending: false,
  },
  {
    key: "cumulative_layout_shift",
    label: "Cumulative Layout Shift",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 0.1, medium: 0.25 },
    ascending: false,
  },
  {
    key: "internal_links",
    label: "Internal Links",
    unit: "",
    min: 0,
    max: 600,
    thresholds: { good: 50, medium: 200 },
    ascending: true,
  },
  {
    key: "external_links",
    label: "External Links",
    unit: "",
    min: 0,
    max: 120,
    thresholds: { good: 5, medium: 50 },
    ascending: false,
  },
  {
    key: "alt_text_coverage",
    label: "Images With Alt (%)",
    unit: "%",
    min: 0,
    max: 100,
    thresholds: { good: 95, medium: 70 },
    ascending: true,
  },
  {
    key: "h1_count",
    label: "H1 Count",
    unit: "",
    min: 0,
    max: 5,
    thresholds: { good: 1, medium: 2 },
    ascending: false,
  },
  {
    key: "title_length",
    label: "Title Length",
    unit: "chars",
    min: 0,
    max: 100,
    thresholds: { good: 65, medium: 49 },
    ascending: true,
  },
  {
    key: "accessibility_score",
    label: "Accessibility Score",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 90, medium: 70 },
    ascending: true,
  },
  {
    key: "seo_score",
    label: "SEO Score",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 90, medium: 70 },
    ascending: true,
  },
  {
    key: "optimization_score",
    label: "Optimization Score",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 90, medium: 70 },
    ascending: true,
  },
  {
    key: "http_status",
    label: "HTTP Status",
    unit: "",
    min: 0,
    max: 600,
    thresholds: { good: 200, medium: 302 },
    ascending: false,
  },
];

export default metricLimits;
