const metricLimits = [
  // Perfomance metrics
  {
    key: "load_time_ms",
    label: "Load Time",
    unit: "ms",
    min: 0,
    max: 4000,
    thresholds: { good: 1000, medium: 3000 },
    ascending: false,
  },
  {
    key: "page_size_kb",
    label: "Page Size",
    unit: "KB",
    min: 0,
    max: 2000,
    thresholds: { good: 500, medium: 1500 },
    ascending: false,
  },
  {
    key: "first_contentful_paint_ms",
    label: "First Contentful Paint",
    unit: "ms",
    min: 0,
    max: 4000,
    thresholds: { good: 1000, medium: 3000 },
    ascending: false,
  },
  {
    key: "largest_contentful_paint_ms",
    label: "Largest Contentful Paint",
    unit: "ms",
    min: 0,
    max: 5000,
    thresholds: { good: 2500, medium: 4000 },
    ascending: false,
  },
  {
    key: "total_blocking_time_ms",
    label: "Total Blocking Time",
    unit: "ms",
    min: 0,
    max: 1000,
    thresholds: { good: 200, medium: 600 },
    ascending: false,
  },
  {
    key: "cumulative_layout_shift",
    label: "Cumulative Layout Shift",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 0.1, medium: 0.25 },
    ascending: false,
  },
  {
    key: "html_size_kb",
    label: "HTML Size",
    unit: "KB",
    min: 0,
    max: 500,
    thresholds: { good: 100, medium: 300 },
    ascending: false,
  },
  {
    key: "number_of_http_requests",
    label: "HTTP Requests",
    unit: "",
    min: 0,
    max: 200,
    thresholds: { good: 50, medium: 100 },
    ascending: false,
  },
  {
    key: "third_party_scripts_count",
    label: "Third-Party Scripts",
    unit: "",
    min: 0,
    max: 50,
    thresholds: { good: 2, medium: 10 },
    ascending: false,
  },

  // Seo metrics
  {
    key: "internal_links",
    label: "Internal Links",
    unit: "",
    min: 0,
    max: 600,
    thresholds: { good: 50, medium: 200 },
    ascending: true,
    source: "seo",
  },
  {
    key: "external_links",
    label: "External Links",
    unit: "",
    min: 0,
    max: 120,
    thresholds: { good: 5, medium: 50 },
    ascending: false,
    source: "seo",
  },
  {
    key: "images_with_alt",
    label: "Images with Alt",
    unit: "%",
    min: 0,
    max: 100,
    thresholds: { good: 95, medium: 70 },
    ascending: true,
    source: "seo",
  },
  {
    key: "images_without_alt",
    label: "Images without Alt",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 0, medium: 5 },
    ascending: false,
    source: "seo",
  },
  {
    key: "h1_count",
    label: "H1 Count",
    unit: "",
    min: 0,
    max: 5,
    thresholds: { good: 1, medium: 2 },
    ascending: false,
  },
  {
    key: "title_length",
    label: "Title Length",
    unit: "chars",
    min: 0,
    max: 100,
    thresholds: { good: 65, medium: 49 },
    ascending: true,
    source: "seo",
  },
  {
    key: "seo_score",
    label: "SEO Score",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 90, medium: 70 },
    ascending: true,
    source: "seo",
  },
  {
    key: "http_statuses",
    label: "HTTP Statuses",
    unit: "",
    min: 0,
    max: 600,
    thresholds: { good: 200, medium: 302 },
    ascending: false,
    source: "seo",
  },

  {
    key: "accessibility_score",
    label: "Accessibility Score",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 90, medium: 70 },
    ascending: true,
  },
  {
    key: "optimization_score",
    label: "Optimization Score",
    unit: "",
    min: 0,
    max: 100,
    thresholds: { good: 90, medium: 70 },
    ascending: true,
  },

  {
    key: "css_minified",
    label: "CSS Minified",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "js_minified",
    label: "JS Minified",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "static_assets_cached",
    label: "Static Assets Cached",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "critical_css_inlined",
    label: "Critical CSS Inlined",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "uses_https",
    label: "Uses HTTPS",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "http2_or_higher",
    label: "HTTP/2 or Higher",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "security_headers_present",
    label: "Security Headers Present",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "viewport_tag_present",
    label: "Viewport Tag Present",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "mobile_friendly",
    label: "Mobile Friendly",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "modern_image_formats_used",
    label: "Modern Image Formats Used",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
  {
    key: "lazy_loading_used",
    label: "Lazy Loading Used",
    unit: "",
    min: 0,
    max: 1,
    thresholds: { good: 1, medium: 0 },
    ascending: true,
  },
];

export default metricLimits;
